---
- name: Configure host.
  hosts: all

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:
    - name: What is the current OS familly?
      ansible.builtin.debug:
        msg: "The current OS is {{ ansible_os_family }} - {{ ansible_distribution }} - {{ ansible_distribution_version }} - {{ ansible_distribution_file_path }}"

    - name: Install NVM
      tags: ['nvm']
      when: install_nvm | bool
      ansible.builtin.include_role:
        name: morgangraphics.ansible_role_nvm
      vars:
        autocomplete: true

    - name: Install Docker
      tags: ['docker']
      become: true
      block:
        - name: Install Docker
          ansible.builtin.include_role:
            name: geerlingguy.docker
