---
- name: Configure host.
  hosts: all

  vars_files:
    - vars/main.yml
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:
    - name: What is the current OS familly?
      ansible.builtin.debug:
        msg: "The current OS is {{ ansible_os_family }} - {{ ansible_distribution }} - {{ ansible_distribution_version }} - {{ ansible_distribution_file_path }}"

    - name: Install Apps Groups
      tags: ['groups']
      ansible.builtin.import_role:
        name: patbriperso.multi_package_installer
      vars:
        apps_groups: "{{ default_apps_groups | combine(my_apps_groups | default({}), recursive=True) }}"

