---
- name: Configure host.
  hosts: all

  vars_files:
    - vars/main.yml
    - default.config.yml

  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  tasks:
    - name: What is the current OS familly?
      ansible.builtin.debug:
        msg: "The current OS is {{ ansible_os_family }} - {{ ansible_distribution }} - {{ ansible_distribution_version }} - {{ ansible_distribution_file_path }}"

    - import_tasks: tasks/sudoers.yml
      when: sudoers.enable

    - name: Install Apps Groups
      tags: ['groups']
      ansible.builtin.import_role:
        name: patbriperso.multi_package_installer
      vars:
        apps_groups: "{{ default_apps_groups | combine(my_apps_groups | default({}), recursive=True) }}"

    - name: Install gocryptfs and mounts
      tags: ['gocryptfs']
      ansible.builtin.import_role:
        name: patbriperso.gocryptfs_user_mounts
      vars:
        gocryptfs_mounts: "{{ gocryptfs.mounts | default([]) }}"

    - name: Install managed configuration
      tags: ['configuration']
      ansible.builtin.import_role:
        name: patbriperso.managed_configs
      vars:
        managed_configs_root: "{{ managed_configs.root | default('') }}"
        managed_configs_links: "{{ managed_configs.links | default([]) }}"
        managed_configs_backup: "{{ managed_configs.backup | default(true) }}"

    - name: Setup rclone automation
      tags: ['rclone_automation']
      ansible.builtin.import_role:
        name: patbriperso.rclone_automation
      vars:
        rclone_automation_script_dir: "{{ rclone_automation.script_dir | default(omit) }}"
        rclone_automations: "{{ rclone_automation.list | default([]) }}"

    - import_tasks: tasks/battery-levels.yml
      tags: ['battery']
      when: battery.enable
