---
roles:
  - name: morgangraphics.ansible_role_nvm
    version: "v2.0.0"
  - name: geerlingguy.docker
  - src: https://github.com/jamescassell/ansible-role-loop.git
collections:
  - name: community.general
